USE sakila;
SET sql_mode="";
SELECT * FROM customer WHERE customer_id = "20";
SELECT * FROM customer WHERE customer_id BETWEEN "20" AND "60";
SELECT * FROM customer WHERE first_name LIKE "l%";
SELECT * FROM customer WHERE first_name LIKE "%l%";
SELECT * FROM customer WHERE first_name LIKE "%l";
SELECT * FROM customer WHERE last_name LIKE "c%" ORDER BY create_date;
SELECT * FROM customer WHERE last_name LIKE "%NN%" ORDER BY create_date DESC LIMIT 5;
SELECT customer_id,first_name,last_name,email FROM customer WHERE customer_id IN ("515","181","582","503","29","85");
SELECT customer_id, store_id, first_name, last_name, email AS email_address, address_id, active, create_date, last_update FROM customer WHERE customer_id = "2";
SELECT first_name, last_name, email FROM customer ORDER BY email DESC;
SELECT customer_id, first_name, last_name, email FROM customer WHERE active IS TRUE AND MONTH(create_date) = "02";
SELECT * FROM customer ORDER BY LENGTH(email) ASC LIMIT 100;